### ISSUE TITLE
POGGERS

### ISSUE THREAD

**Issue by LegendaryEmoji** [Snowflake107/pog#2]
POGGGG POGGERGP POPOPOPOP POGGERS POGGER POG POG POG POGERS POGGGERS POGGER POGER POG POG POG

**Comment by CTK-WARRIOR** [comment]
POGGGG POGGERGP POPOPOPOP POGGERS POGGER POG POG POG POGERS POGGGERS POGGER POGER POG POG POG

**Comment by LegendaryEmoji** [comment]
POGGGG POGGERGP POPOPOPOP POGGERS POGGER POG POG POG POGERS POGGGERS POGGER POGER POG POG POG

**Comment by CTK-WARRIOR** [comment]
how to go into bathroom?

**Comment by LegendaryEmoji** [comment]
by going

**Comment by CTK-WARRIOR** [comment]
but how

**Comment by LegendaryEmoji** [comment]
wdym how, just go wtf

**Comment by CTK-WARRIOR** [comment]
i am bit shy >.<

**Comment by LegendaryEmoji** [comment]
idc just go lol

**Comment by LegendaryEmoji** [comment]
closing this issue because too many metal patients

**Comment by abh80** [comment]
kok

**Comment by CTK-WARRIOR** [comment]
alola

**Comment by CTK-WARRIOR** [comment]
will you help me

**Comment by abh80** [comment]
hi

**Comment by LegendaryEmoji** [comment]
no sorry

**Comment by abh80** [comment]
kok

**Comment by LegendaryEmoji** [comment]
wut kok lol its kek

**Comment by CTK-WARRIOR** [comment]
i want to do it

**Comment by abh80** [comment]
kek

**Comment by LegendaryEmoji** [comment]
do it then

**Comment by abh80** [comment]
nice chat brw

**Comment by LegendaryEmoji** [comment]
stop 🛑

**Comment by abh80** [comment]
@LegendaryEmoji consider reponing the issue

**Comment by LegendaryEmoji** [comment]
no

**Comment by abh80** [comment]
k

**Comment by CTK-WARRIOR** [comment]
### HELP
```i.need.help```

**Comment by LegendaryEmoji** [comment]
NO HELP FOR NUBS

**Comment by abh80** [comment]
<img src = "https://cdn.discordapp.com/attachments/702028690439274526/790515626815914025/750253062689652768.png" />

**Comment by LegendaryEmoji** [comment]
wut

**Comment by CTK-WARRIOR** [comment]
shutup nerd with 0 braincells 
![](https://camo.githubusercontent.com/1e530e17ee838bc553b510d37fdea810d7009d822570f37f0baab854e61c896c/68747470733a2f2f63646e2e646973636f72646170702e636f6d2f6174746163686d656e74732f3730323032383639303433393237343532362f3739303531353632363831353931343032352f3735303235333036323638393635323736382e706e67)

**Comment by LegendaryEmoji** [comment]
NO U

**Comment by abh80** [comment]
yes
<img src ="https://cdn.discordapp.com/attachments/702028690439274526/790515626815914025/750253062689652768.png"/>

**Comment by LegendaryEmoji** [comment]
stfu

**Comment by Snowflake107** [comment]
pog

**Comment by abh80** [comment]
pog

**Comment by LegendaryEmoji** [comment]
***pog***

**Comment by CTK-WARRIOR** [comment]
pog

**Comment by abh80** [comment]
Pog
